CREATE TABLE Appointments (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES Entities(Id) ON DELETE CASCADE
	,TreatmentId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Treatments(Id) --ON DELETE CASCADE
	,PatientId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Patients(Id) --ON DELETE CASCADE
	,DoctorId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Doctors(Id) --ON DELETE CASCADE
	);
